### ISSUE TITLE
Error: Page crashed!

### ISSUE THREAD

**Issue by hista** [kostia7alania/badoo_autolikes_bot#8]
Hi,
I am facing an issue:
```
npm run start

> badoo_autolikes_bot@1.0.0 start
> node src/

/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Page.js:213
    this.emit('error', new Error('Page crashed!'));
                       ^

Error: Page crashed!
    at Page._onTargetCrashed (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.<anonymous> (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Page.js:122:56)
    at CDPSession.emit (node:events:513:28)
    at CDPSession._onMessage (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Connection.js:112:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on Page instance at:
    at Page._onTargetCrashed (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Page.js:213:10)
    at CDPSession.<anonymous> (/home/hista/badoo_autolikes_bot/node_modules/puppeteer/lib/Page.js:122:56)
    [... lines matching original stack trace ...]
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.9.1
```

Could you please tell me how to fix it?

Thanks for your kind help :)

**Comment by chriscoderdr** [comment]
@hista I made a PR that fixes this and improve the code a little bit:
https://github.com/kostia7alania/badoo_autolikes_bot/pull/9
While it gets merge you could use my main branch.

https://github.com/chriscoderdr/badoo_autolikes_bot
